# Generated by Django 3.2.7 on 2021-11-09 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_catastral', models.CharField(max_length=50, null=True, verbose_name='cedula catastral')),
                ('direccion', models.CharField(max_length=200, verbose_name='direccion')),
                ('tipo', models.CharField(choices=[('1', 'urbano'), ('2', 'rural')], default='urbano', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='nombre')),
                ('identificacion', models.CharField(max_length=50, verbose_name='identificacion')),
                ('predios', models.ManyToManyField(through='pages.Matricula', to='pages.Predio')),
            ],
        ),
        migrations.AddField(
            model_name='predio',
            name='propietarios',
            field=models.ManyToManyField(through='pages.Matricula', to='pages.Propietario'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.predio'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.propietario'),
        ),
    ]
