# Generated by Django 3.2.7 on 2021-11-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='tipo',
            field=models.CharField(choices=[('urbano', 'Urbano'), ('urbano', 'Rural')], default='urbano', max_length=40),
        ),
    ]
