# Generated by Django 3.2.7 on 2021-11-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_predio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='tipo',
            field=models.CharField(choices=[('urbano', 'Urbano'), ('rural', 'Rural')], max_length=40),
        ),
    ]
