# Generated by Django 3.2.7 on 2021-11-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20211110_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='cedula_catastral',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='cedula catastral'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='identificacion',
            field=models.CharField(max_length=50, unique=True, verbose_name='identificacion'),
        ),
    ]
