# Generated by Django 3.2.7 on 2021-11-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20211110_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='direccion',
            field=models.CharField(max_length=200, unique=True, verbose_name='direccion'),
        ),
    ]
